--- 
- hosts: 10.100.0.107
  become: yes
  vars:
    mysql_root_pass: root
  tasks: 
    - name: install apache2 
      apt: name=apache2 update_cache=yes state=latest
    - name: install emacs
      apt: name=emacs
    - name: install make
      apt: name=make
    - name: install git
      apt: name=git
    - name: python
      apt: name=python
    - name: python-pip
      apt: name=python-pip
    - name: python setuptools
      apt: name=python-setuptools*
    - name: MOD WSGI
      apt: name=libapache2-mod-wsgi
    - name: Python developer tools
      apt: name=python-dev
    - name: lib
      apt: name=libmysqld-dev
    - name: Set MySQL root password before installing
      debconf: name='mysql-server' question='mysql-server/root_password' value='{{mysql_root_pass | quote}}' vtype='password'
    - name: Confirm MySQL root password before installing
      debconf: name='mysql-server' question='mysql-server/root_password_again' value='{{mysql_root_pass | quote}}' vtype='password'
    - name: Install MySQL
      apt: name=mysql-server state=installed
    - name: Python mySQL db 
      apt: name=python-mysqldb
    - name: update mysql root password for all root accounts
      sudo: yes
      mysql_user:
        name: root
        password: "{{ mysql_root_pass }}"
        login_user: root
        login_password: "{{ mysql_root_pass }}"
        check_implicit_admin: yes
        priv: "*.*:ALL,GRANT"
    - name: create a file in remote machine to store mysql credentials
      copy:
        dest: "~/.my.cnf"
        content: |
          login_user=root
          login_password=root
    - name: move mysql config file to root
      shell: sudo mv ~/.my.cnf /root/

    - name: Create a new database with name 'outreach'
      mysql_db:
        name: outreach
        state: present
    - name: pip package 
      pip: name=Flask
    - name: pip package 
      pip: name=Flask-cors
    - name: pip package 
      pip: name=Flask-testing
    - name: pip package 
      pip: name=Flask-OAuthlib
    - name: pip package 
      pip: name=oursql
    - name: pip package 
      pip: name=Flask-SQLAlchemy
    - name: clonig outreach repo from github
      git: 
         repo: https://github.com/vlead/outreach-portal.git
         dest: /home/ubuntu/outreach